spring.profiles.active: ${spring.profiles.active}
---
server:
  port: 8761
spring.profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
---
server:
  port: 8761
spring.profiles: peer-one
eureka:
  instance:
    hostname: localhost
  client:
   serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8771}/eureka/
---
server:
  port: 8771
spring.profiles: peer-two
eureka:
  instance:
    hostname: localhost
  client:
   serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/